### ISSUE TITLE
License file is empty [vm-license]

### ISSUE THREAD

**Issue by anshitasayal** [SoftwareEngineeringToolDemos/ICSE-2014-LTSA_PCA#15]
There is a license file on the desktop which is empty and does not have any license associated with the tool on the VM.

**Comment by spati2** [comment]
There is no license available for the tool as specified in the file

**Comment by anshitasayal** [comment]
The tool being open source software has no license associated with it on the official website as well. Hence closing the issue.

**Comment by anshitasayal** [comment]
@spati2 is getting in touch with the authors of the tool to get a final confirmation on the existence/non existence of tool's license.

**Comment by spati2** [comment]
Closing issue as no answer has been received from the authors on the matter. Also no license present on the official website
